# Generated by Django 4.0.4 on 2022-04-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_level_alter_comment_lft_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("pk",)},
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["post"], name="comments_co_post_id_380fdd_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["parent"], name="comments_co_parent__fdf1ec_idx"),
        ),
    ]
