version: '3'

volumes:
  krivov_local_postgres_data: {}
  krivov_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: krivov_local_django
    container_name: krivov_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: krivov_local_postgres
    container_name: krivov_local_postgres
    volumes:
      - krivov_local_postgres_data:/var/lib/postgresql/data:Z
      - krivov_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.postgres
